### ISSUE TITLE
[feat] 구현 background execution

### ISSUE THREAD

**Issue by geee3** [DeveloperAcademy-POSTECH/MC3-Team7-TopiaCorp.#2]
## 🐰 Description
background execution 구현

## 🧑‍💻 Todo
- [x] Handle background events
- [x] Transition from the foreground
- [x] https://speakerdeck.com/kakao/darineun-geoleul-bbun-dot-manbogi-seobiseu-gaebalgi?slide=68
- [x] https://developer.apple.com/videos/play/wwdc2019/707
- [x] https://developer.apple.com/videos/play/wwdc2020/10063

## ✏️ ETC
- https://stackoverflow.com/questions/46148399/in-ios-11-devicemotion-in-background-stopped-working
- [https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/about_the_background_execution_sequence#2928660](url)
- https://www.reddit.com/r/swift/comments/10ul63p/xcode_swift_how_can_i_use_core_motion_when_app_is/
- https://www.youtube.com/watch?v=tRpHiE6PABU&list=LL&index=1&t=13s
- https://www.youtube.com/watch?v=YpDguDapD1c&list=LL&index=2&t=6s
- https://www.youtube.com/watch?v=k484qxm8iyI&list=LL&index=3&t=1s
- https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/about_the_background_execution_sequence#2928660
