### ISSUE TITLE
[feat] 구현 background execution

### ISSUE THREAD

**Issue by geee3** [DeveloperAcademy-POSTECH/MC3-Team7-TopiaCorp.#43]
## 🐰 Description
구현 background execution

## 🧑‍💻 Todo
- [x] 측정 시작시 음악 재생
- [x] 일시 정지시 음악 종료
- [x] 측정 종료시 음악 종료

## ✏️ ETC
