### ISSUE TITLE
[bug] 수정 잡다한 버그들

### ISSUE THREAD

**Issue by LIM-YUSANG** [DeveloperAcademy-POSTECH/MC3-Team7-TopiaCorp.#73]
## 🐰 Description
에어팟 뺐을때 모든 뷰에서 모달뷰 뜨기

## 🧑‍💻 Todo
- [ ] 모든뷰에서 에어팟 뺐을때 모달뷰로
- [ ] 물 0L 될때 감지해서 faleView 뜨게하기
- [ ] 일시정지 누르고 에어팟 뺐을때 자동시작 안하게

## ✏️ ETC
